package modelo.entity;
// Generated 25/05/2018 02:01:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sessao generated by hbm2java
 */
public class Sessao  implements java.io.Serializable {


     private Integer idSessao;
     private double aie;
     private double afe;
     private double aid;
     private double afd;
     private Date registro;

    public Sessao() {
    }

    public Sessao(double aie, double afe, double aid, double afd, Date registro) {
       this.aie = aie;
       this.afe = afe;
       this.aid = aid;
       this.afd = afd;
       this.registro = registro;
    }
   
    public Integer getIdSessao() {
        return this.idSessao;
    }
    
    public void setIdSessao(Integer idSessao) {
        this.idSessao = idSessao;
    }
    public double getAie() {
        return this.aie;
    }
    
    public void setAie(double aie) {
        this.aie = aie;
    }
    public double getAfe() {
        return this.afe;
    }
    
    public void setAfe(double afe) {
        this.afe = afe;
    }
    public double getAid() {
        return this.aid;
    }
    
    public void setAid(double aid) {
        this.aid = aid;
    }
    public double getAfd() {
        return this.afd;
    }
    
    public void setAfd(double afd) {
        this.afd = afd;
    }
    public Date getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Date registro) {
        this.registro = registro;
    }




}


